version: '3'

services:
  nginx:
      image: nginx:1.13
      ports:
        - "8000:8000"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./src/static:/static
        - ./logs/nginx:/var/log/nginx
      depends_on:
        - python
  
  redis:
    image: redis:alpine
    expose:
      - "6379"

  db:
      image: mysql:5.7
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
      
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: django_app
        MYSQL_USER: django_app
        MYSQL_PASSWORD: django_app
        TZ: 'Asia/Tokyo'
      volumes:
        - ./mysql:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d

  python:
      build: ./python
      command: sh /tmp/django_exec.sh
      volumes:
        - ./src:/code
        - ./src/static:/static
        - ./logs/django:/logs
        - ./deploy:/tmp
      environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_DEFAULT_OUTPUT: json 
      expose:
        - "8001"
        - "3001"
      depends_on:
        - db
        - redis
