# Generated by Django 2.0.4 on 2020-05-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'address_regions',
            },
        ),
        migrations.CreateModel(
            name='Address_states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_region_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'address_states',
            },
        ),
        migrations.CreateModel(
            name='Employee_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('auth_application', models.IntegerField(default=0)),
                ('sales_application', models.IntegerField(default=0)),
                ('clients_application', models.IntegerField(default=0)),
                ('constructions_application', models.IntegerField(default=0)),
                ('partner_companies_application', models.IntegerField(default=0)),
                ('accounting_application', models.IntegerField(default=0)),
                ('merchandise_order_application', models.IntegerField(default=0)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'employee_groups',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('kana', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=13, null=True)),
                ('password', models.CharField(max_length=255)),
                ('address_state_id', models.IntegerField()),
                ('city', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('building', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255, null=True)),
                ('relationship', models.CharField(max_length=255, null=True)),
                ('emergency_contact_address', models.CharField(max_length=255, null=True)),
                ('emergency_contact_tel', models.CharField(max_length=13, null=True)),
                ('emergency_contact_email', models.CharField(max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('qualification_acquisition_date', models.DateField(blank=True, null=True)),
                ('qualification_type', models.IntegerField(null=True)),
                ('qualification_remarks', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('updated_user_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('employee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.Employee_groups', verbose_name='社員グループID')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
