# Generated by Django 2.2.14 on 2020-07-06 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='作成日付')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新日付')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='削除日付')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Skill_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Skill_deleted', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Skill_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('tel', models.CharField(max_length=11, null=True)),
                ('postcode', models.CharField(max_length=7, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('building', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Partner_created', to=settings.AUTH_USER_MODEL)),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Partner_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Partner_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
