# Generated by Django 2.2.14 on 2020-07-06 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('tel', models.CharField(max_length=11, null=True)),
                ('postcode', models.CharField(max_length=7, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('building', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Client_created', to=settings.AUTH_USER_MODEL)),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Client_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Client_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='案件名')),
                ('description', models.TextField(max_length=2000, verbose_name='案件概要')),
                ('location', models.CharField(max_length=255, verbose_name='現場')),
                ('project_date', models.DateField(verbose_name='案件日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('created_at', models.DateTimeField(verbose_name='作成日付')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日付')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日付')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Client', verbose_name='顧客')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Project_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Project_deleted', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('partners', models.ManyToManyField(blank=True, to='engineers.Partner', verbose_name='取引先')),
                ('skills', models.ManyToManyField(blank=True, to='engineers.Skill', verbose_name='資格')),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Project_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('level', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('sort_order', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'choices',
                'unique_together': {('code', 'level', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='ステータス')),
                ('engineer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='技術者')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project', verbose_name='案件')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
