# Generated by Django 2.2.12 on 2020-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
