# Generated by Django 2.2.14 on 2020-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=1, verbose_name='ステータス'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default=1, max_length=2000, verbose_name='資格'),
            preserve_default=False,
        ),
    ]
