# Generated by Django 2.2.12 on 2020-05-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_auto_20200523_0855'),
        ('projects', '0002_auto_20200522_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, to='engineers.Partner', verbose_name='取引先'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Client', verbose_name='顧客'),
        ),
    ]
