# Generated by Django 2.2.12 on 2020-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_auto_20200523_0855'),
        ('accounts', '0003_auto_20200522_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=1, max_length=2000, verbose_name='詳細'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='engineers.Skill', verbose_name='資格'),
        ),
    ]
